import { Classroom } from "../models/classroom.model.js";
import { AcademicYear } from "../models/academic-year.model.js";
import { Student } from "../models/student.model.js";
import { AppError } from "../utils/AppError.js";
import { writeAudit } from "./audit.service.js";
const dataOf=(b)=>{const className=String(b.className??"").trim(),section=String(b.section??"").trim(); const capacity=b.capacity===""||b.capacity==null?null:Number(b.capacity); if(!className||!section) throw new AppError("className and section are required.",400); if(capacity!==null&&(!Number.isInteger(capacity)||capacity<1||capacity>10000)) throw new AppError("capacity must be an integer between 1 and 10000.",400); return {className,section,capacity};};
export const listClassrooms=async(q)=>{const filter={}; if(q.academicYear) filter.academicYear=q.academicYear; if(q.includeInactive!=="true") filter.isActive=true; const rooms=await Classroom.find(filter).populate("academicYear","name isActive").sort({className:1,section:1}).lean(); return Promise.all(rooms.map(async r=>({...r,studentCount:await Student.countDocuments({class:r.className,section:r.section,isDeleted:{$ne:true},status:"active"})})));};
export const createClassroom=async(b,requestId)=>{const data=dataOf(b); const year=await AcademicYear.findById(b.academicYear); if(!year||year.isArchived) throw new AppError("Valid academicYear is required.",400); const room=await Classroom.create({...data,academicYear:year._id}); await writeAudit({entityType:"classroom",entityId:room._id,action:"CREATE",changes:{after:room.toObject()},requestId}); return room;};
export const updateClassroom=async(id,b,requestId)=>{const room=await Classroom.findById(id); if(!room) throw new AppError("Classroom not found.",404); const before=room.toObject(); Object.assign(room,dataOf({...room.toObject(),...b})); if(typeof b.isActive==="boolean") room.isActive=b.isActive; await room.save(); await writeAudit({entityType:"classroom",entityId:room._id,action:"UPDATE",changes:{before,after:room.toObject()},requestId}); return room;};
